## Part 1: Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [ ]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [ ]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

# Display the first few rows of y_df
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [ ]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    'Education',
    'Age',
    'DistanceFromHome',
    'JobSatisfaction',
    'OverTime',
    'StockOptionLevel',
    'WorkLifeBalance',
    'YearsAtCompany',
    'YearsSinceLastPromotion',
    'NumCompaniesWorked'
]

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
X_df.dtypes



Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [ ]:

from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_df, y_df, test_size=0.2, random_state=42
)

# Display the shapes of the resulting datasets
X_train.shape, X_test.shape, y_train.shape, y_test.shape



((1176, 10), (294, 10), (1176, 2), (294, 2))

In [ ]:
# Convert the 'OverTime' column to numeric using map
X_train['OverTime'] = X_train['OverTime'].map({'No': 0, 'Yes': 1})
X_test['OverTime'] = X_test['OverTime'].map({'No': 0, 'Yes': 1})

# Verify the conversion in X_train
X_train['OverTime'].value_counts()


OverTime
0    837
1    339
Name: count, dtype: int64

In [ ]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Display the first few rows of the scaled training data
X_train_scaled[:5]


array([[-0.86335572, -1.38855944,  1.44039645, -1.58233648, -0.63641018,
         2.54747106,  0.3574354 , -0.97426331, -0.67610953, -1.05916816],
       [-0.86335572, -2.04073779, -0.52269928,  1.15283407, -0.63641018,
        -0.94552463,  0.3574354 , -1.13857331, -0.67610953, -0.65943075],
       [-0.86335572, -0.84507748,  1.31770296,  1.15283407, -0.63641018,
         0.21880727,  0.3574354 , -0.6456433 , -0.67610953, -0.25969335],
       [ 0.09993302,  0.24188644,  0.3361551 , -0.67061296, -0.63641018,
        -0.94552463,  0.3574354 , -0.3170233 , -0.35524399,  0.53978146],
       [ 0.09993302, -0.62768469,  1.31770296,  0.24111056, -0.63641018,
         0.21880727,  0.3574354 ,  0.50452672, -0.67610953, -0.65943075]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder


In [ ]:
# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the Department column in the training data
dept_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder to the training and testing data
dept_train_encoded = dept_encoder.transform(y_train[['Department']])
dept_test_encoded = dept_encoder.transform(y_test[['Department']])

# Display the first few rows of the encoded training data
dept_train_encoded[:5]


array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [ ]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the Attrition column in the training data
attrition_encoder.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder to the training and testing data
attrition_train_encoded = attrition_encoder.transform(y_train[['Attrition']])
attrition_test_encoded = attrition_encoder.transform(y_test[['Attrition']])

# Display the first few rows of the encoded training data
attrition_train_encoded[:5]



array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Create, Compile, and Train the Model

In [ ]:
from tensorflow.keras.layers import Input, Dense

In [ ]:
# Find the number of columns in the X training data
input_dim = X_train_scaled.shape[1]

# Create the input layer
input_layer = Input(shape=(input_dim,))

# Create at least two shared layers
shared_layer_1 = Dense(16, activation='relu')(input_layer)
shared_layer_2 = Dense(8, activation='relu')(shared_layer_1)

# Output the summary of the shared layers
shared_layer_2


<KerasTensor shape=(None, 8), dtype=float32, sparse=False, name=keras_tensor_16>

In [ ]:
# Create a branch for Department with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer = Dense(4, activation='relu')(shared_layer_2)

# Create the output layer
dept_output_layer = Dense(dept_train_encoded.shape[1], activation='softmax', name='department_output')(dept_hidden_layer)

# Output the summary of the department branch
dept_output_layer



<KerasTensor shape=(None, 3), dtype=float32, sparse=False, name=keras_tensor_18>

In [ ]:
# Create a branch for Attrition with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden_layer = Dense(4, activation='relu')(shared_layer_2)

# Create the output layer
attrition_output_layer = Dense(attrition_train_encoded.shape[1], activation='softmax', name='attrition_output')(attrition_hidden_layer)

# Output the summary of the attrition branch
attrition_output_layer


<KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_20>

In [ ]:
# Create a branch for Attrition with a hidden layer and an output layer
attrition_hidden_layer = Dense(4, activation='relu')(shared_layer_2)
attrition_output_layer = Dense(2, activation='softmax', name='attrition_output')(attrition_hidden_layer)


In [ ]:
# Create the model
model = Model(
    inputs=input_layer,
    outputs=[dept_output_layer, attrition_output_layer]
)

# Compile the model
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',
        'attrition_output': 'categorical_crossentropy',
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy',
    }
)

# Summarize the model
model.summary()


Model: "functional_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2             │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_8 (Dense)           │ (None, 16)             │            176 │ input_layer_2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_9 (Dense)           │ (None, 8)              │            136 │ dense_8[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_10 (Dense)          │ (None, 4)              │             36 │ dense_9[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_12 (Dense)          │ (None, 4)              │             36 │ dense_9[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             15 │ dense_10[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             10 │ dense_12[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 409 (1.60 KB)

 Trainable params: 409 (1.60 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
!pip install --upgrade tensorflow


In [ ]:
# Simplified model for attrition output
attrition_model = Model(inputs=input_layer, outputs=attrition_output_layer)

# Compile the simplified model
attrition_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the simplified attrition model
try:
    attrition_history = attrition_model.fit(
        X_train_scaled,
        attrition_train_encoded,
        validation_data=(X_test_scaled, attrition_test_encoded),
        epochs=10,
        batch_size=32
    )
except Exception as e:
    print("Error during attrition-only model training:", str(e))


Epoch 1/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - accuracy: 0.8255 - loss: 0.5343 - val_accuracy: 0.8673 - val_loss: 0.4778
Epoch 2/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 66ms/step - accuracy: 0.8220 - loss: 0.4995 - val_accuracy: 0.8673 - val_loss: 0.4396
Epoch 3/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8218 - loss: 0.4676 - val_accuracy: 0.8673 - val_loss: 0.4199
Epoch 4/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8238 - loss: 0.4342 - val_accuracy: 0.8673 - val_loss: 0.4079
Epoch 5/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8281 - loss: 0.3974 - val_accuracy: 0.8707 - val_loss: 0.4003
Epoch 6/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8431 - loss: 0.3763 - val_accuracy: 0.8707 - val_loss: 0.3956
Epoch 7/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.8233 - loss: 0.3981 - val_accuracy: 0.8776 - val_loss: 0.3933
Epoch 8/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8338 - loss: 0.3905 - val_accuracy: 0.8741 - v

In [ ]:
# Attrition branch
attrition_hidden_layer = Dense(4, activation='relu')(shared_layer_2)
attrition_output_layer = Dense(2, activation='softmax', name='attrition_output')(attrition_hidden_layer)


In [ ]:
# Validate model predictions for a small batch
test_predictions = model.predict(X_train_scaled[:5])

# Check prediction shapes
print("Department output shape (model):", test_predictions[0].shape)  # Should be (5, 3)
print("Attrition output shape (model):", test_predictions[1].shape)  # Should be (5, 2)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step
Department output shape (model): (5, 3)
Attrition output shape (model): (5, 2)


In [ ]:
# Simplified model for attrition output
attrition_model = Model(inputs=input_layer, outputs=attrition_output_layer)

# Compile the attrition model
attrition_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the attrition model
try:
    attrition_history = attrition_model.fit(
        X_train_scaled,
        attrition_train_encoded,
        validation_data=(X_test_scaled, attrition_test_encoded),
        epochs=1,
        batch_size=32
    )
    print("Attrition-only training successful.")
except Exception as e:
    print("Error during attrition-only training:", str(e))


37/37 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.2294 - loss: 0.7641 - val_accuracy: 0.5272 - val_loss: 0.7083
Attrition-only training successful.


In [ ]:
# Simplify the model compilation
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',
        'attrition_output': 'categorical_crossentropy',
    },
    metrics=['accuracy']  # Use a single metric for all outputs
)

print("Model recompiled with simplified metrics.")


Model recompiled with simplified metrics.


In [ ]:
import tensorflow.keras.backend as K

# Forcefully reset the TensorFlow session
K.clear_session()
print("TensorFlow session has been reset.")


TensorFlow session has been reset.


In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

# Recreate the input layer and shared layers
input_layer = Input(shape=(X_train_scaled.shape[1],))

# Shared layers
shared_layer_1 = Dense(16, activation='relu')(input_layer)
shared_layer_2 = Dense(8, activation='relu')(shared_layer_1)

# Department branch
dept_hidden_layer = Dense(4, activation='relu')(shared_layer_2)
dept_output_layer = Dense(3, activation='softmax', name='department_output')(dept_hidden_layer)

# Attrition branch
attrition_hidden_layer = Dense(4, activation='relu')(shared_layer_2)
attrition_output_layer = Dense(2, activation='softmax', name='attrition_output')(attrition_hidden_layer)

# Combine the model
model = Model(inputs=input_layer, outputs=[dept_output_layer, attrition_output_layer])

# Compile the model
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',
        'attrition_output': 'categorical_crossentropy',
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy',
    }
)

# Log model summary
print("Model Summary:")
model.summary()

# Validate predictions for a single sample
predictions = model.predict(X_train_scaled[:1])
print("Predicted department output shape:", predictions[0].shape)  # Should be (1, 3)
print("Predicted attrition output shape:", predictions[1].shape)  # Should be (1, 2)

print("Cell 21 setup complete.")


Model Summary:


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 16)             │            176 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 8)              │            136 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 4)              │             36 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 4)              │             36 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             15 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             10 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 409 (1.60 KB)

 Trainable params: 409 (1.60 KB)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
Predicted department output shape: (1, 3)
Predicted attrition output shape: (1, 2)
Cell 21 setup complete.


In [ ]:
# Print the configuration of the attrition output layer
print("Attrition output layer configuration:")
print(model.get_layer('attrition_output').get_config())

# Print the configuration of the department output layer
print("Department output layer configuration:")
print(model.get_layer('department_output').get_config())


Attrition output layer configuration:
{'name': 'attrition_output', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'units': 2, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
Department output layer configuration:
{'name': 'department_output', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'units': 3, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_na

In [ ]:
# Validate predictions for a small batch
predictions = model.predict(X_train_scaled[:4])
print("Predicted department output shape:", predictions[0].shape)  # Expected: (4, 3)
print("Predicted attrition output shape:", predictions[1].shape)  # Expected: (4, 2)

# Inspect the actual predictions for attrition_output
print("Sample predictions for attrition_output:")
print(predictions[1])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
Predicted department output shape: (4, 3)
Predicted attrition output shape: (4, 2)
Sample predictions for attrition_output:
[[0.35838398 0.64161605]
 [0.48045066 0.5195493 ]
 [0.42085093 0.57914907]
 [0.48306018 0.5169398 ]]


In [ ]:
# Simplify the model to only the attrition branch
attrition_model = Model(inputs=input_layer, outputs=attrition_output_layer)

# Compile the attrition-only model
attrition_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the attrition branch only
try:
    attrition_history = attrition_model.fit(
        X_train_scaled,
        attrition_train_encoded,
        validation_data=(X_test_scaled, attrition_test_encoded),
        epochs=1,
        batch_size=8
    )
    print("Attrition-only training completed successfully.")
except Exception as e:
    print("Error during attrition-only training:", str(e))

147/147 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.4219 - loss: 0.7533 - val_accuracy: 0.8605 - val_loss: 0.5361
Attrition-only training completed successfully.


In [ ]:
# Validate target shapes and content
print("Department target shape (training):", dept_train_encoded[:8].shape)  # Should be (8, 3)
print("Attrition target shape (training):", attrition_train_encoded[:8].shape)  # Should be (8, 2)

# Check the first few rows of each target
print("Sample department target data:\n", dept_train_encoded[:8])
print("Sample attrition target data:\n", attrition_train_encoded[:8])


Department target shape (training): (8, 3)
Attrition target shape (training): (8, 2)
Sample department target data:
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Sample attrition target data:
 [[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [ ]:
import tensorflow as tf
tf.get_logger().setLevel('ERROR')


In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.18.0


In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

# Recreate the model from scratch
input_layer = Input(shape=(X_train_scaled.shape[1],))

# Shared layers
shared_layer_1 = Dense(16, activation='relu')(input_layer)
shared_layer_2 = Dense(8, activation='relu')(shared_layer_1)

# Department branch
dept_hidden_layer = Dense(4, activation='relu')(shared_layer_2)
dept_output_layer = Dense(3, activation='softmax', name='department_output')(dept_hidden_layer)

# Attrition branch
attrition_hidden_layer = Dense(4, activation='relu')(shared_layer_2)
attrition_output_layer = Dense(2, activation='softmax', name='attrition_output')(attrition_hidden_layer)

# Combine the model
model = Model(inputs=input_layer, outputs=[dept_output_layer, attrition_output_layer])

# Compile the model
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',
        'attrition_output': 'categorical_crossentropy',
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy',
    }
)

print("Model recompiled successfully.")


Model recompiled successfully.


In [ ]:
# Class weights for imbalanced targets
class_weights = {
    'department_output': {0: 5, 1: 1, 2: 2},
    'attrition_output': {0: 0.2, 1: 5}
}

# Train department branch
department_model = Model(inputs=input_layer, outputs=dept_output_layer)
department_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
dept_history = department_model.fit(
    X_train_scaled,
    dept_train_encoded,
    validation_data=(X_test_scaled, dept_test_encoded),
    epochs=10,
    batch_size=32,
    class_weight=class_weights['department_output'],  # Include class weights
    verbose=1
)

# Train attrition branch
attrition_model = Model(inputs=input_layer, outputs=attrition_output_layer)
attrition_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
attrition_history = attrition_model.fit(
    X_train_scaled,
    attrition_train_encoded,
    validation_data=(X_test_scaled, attrition_test_encoded),
    epochs=10,
    batch_size=32,
    class_weight=class_weights['attrition_output'],  # Include class weights
    verbose=1
)


Epoch 1/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.6418 - loss: 1.8674 - val_accuracy: 0.6156 - val_loss: 0.9339
Epoch 2/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6103 - loss: 1.5785 - val_accuracy: 0.5952 - val_loss: 0.9491
Epoch 3/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5643 - loss: 1.5530 - val_accuracy: 0.5918 - val_loss: 0.9480
Epoch 4/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5651 - loss: 1.5364 - val_accuracy: 0.5714 - val_loss: 0.9439
Epoch 5/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5327 - loss: 1.5088 - val_accuracy: 0.5340 - val_loss: 0.9412
Epoch 6/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5905 - loss: 1.4360 - val_accuracy: 0.5204 - val_loss: 0.9366
Epoch 7/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5397 - loss: 1.5292 - val_accuracy: 0.5306 - val_loss: 0.9370
Epoch 8/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5443 - loss: 1.5269 - val_accuracy: 0.5204 - val_loss

In [ ]:
# Make predictions using the trained models
dept_predictions = department_model.predict(X_test_scaled[:4])
attrition_predictions = attrition_model.predict(X_test_scaled[:4])

print("Department predictions:")
print(dept_predictions)

print("Attrition predictions:")
print(attrition_predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Department predictions:
[[0.05925125 0.7473255  0.19342324]
 [0.22255123 0.37783602 0.39961272]
 [0.10415388 0.6480786  0.24776754]
 [0.14471851 0.44139788 0.41388354]]
Attrition predictions:
[[0.154816   0.84518397]
 [0.40375707 0.59624296]
 [0.21137702 0.788623  ]
 [0.31889403 0.68110603]]


In [ ]:
from sklearn.metrics import classification_report, accuracy_score

# Make predictions for the department and attrition branches
dept_test_predictions = department_model.predict(X_test_scaled)
attrition_test_predictions = attrition_model.predict(X_test_scaled)

# Decode department predictions
dept_predicted_classes = dept_test_predictions.argmax(axis=1)
dept_true_classes = dept_test_encoded.argmax(axis=1)

# Decode attrition predictions
attrition_predicted_classes = (attrition_test_predictions[:, 0] > 0.5).astype(int)  # Threshold at 0.5
attrition_true_classes = attrition_test_encoded.argmax(axis=1)

# Department branch evaluation
print("Department Branch Evaluation:")
print("Classification Report:")
print(classification_report(dept_true_classes, dept_predicted_classes))
print("Accuracy:", accuracy_score(dept_true_classes, dept_predicted_classes))

# Attrition branch evaluation
print("\nAttrition Branch Evaluation:")
print("Classification Report:")
print(classification_report(attrition_true_classes, attrition_predicted_classes))
print("Accuracy:", accuracy_score(attrition_true_classes, attrition_predicted_classes))



10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step  
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 
Department Branch Evaluation:
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        13
           1       0.66      0.69      0.68       196
           2       0.28      0.29      0.29        85

    accuracy                           0.54       294
   macro avg       0.31      0.33      0.32       294
weighted avg       0.52      0.54      0.53       294

Accuracy: 0.54421768707483

Attrition Branch Evaluation:
Classification Report:
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       255
           1       0.00      0.00      0.00        39

    accuracy                           0.87       294
   macro avg       0.43      0.50      0.46       294
weighted avg       0.75      0.87      0.81       294

Accuracy: 0.8673469387755102


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/m

In [ ]:
# Print accuracy for department and attrition branches
print(f"Department Branch Accuracy: {accuracy_score(dept_true_classes, dept_predicted_classes):.2f}")
print(f"Attrition Branch Accuracy: {accuracy_score(attrition_true_classes, attrition_predicted_classes):.2f}")


Department Branch Accuracy: 0.54
Attrition Branch Accuracy: 0.87


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. **Is accuracy the best metric to use on this data? Why or why not?**

Not really. Accuracy is useful, but it doesn't tell the whole story with this kind of data. Here's why:

For Attrition, the data is super imbalanced—way more people stay (0) than leave (1). So, a model could just predict "everyone stays" and still get high accuracy, which wouldn’t be helpful. For Department, one department is way bigger than the others, so accuracy might just reflect the model picking the most common department.

Instead, we should focus on:

Precision: Helps us avoid false positives, like incorrectly predicting someone might leave their job when they're actually happy.
Recall: Helps us catch what really matters, like correctly identifying employees at risk of leaving.
F1-Score: A good balance of precision and recall, especially useful when data is uneven.
What really matters?

For Attrition, recall might be the priority—you want to catch as many at-risk employees as possible to take action.
For Department, precision might matter more—it’s better to be sure when assigning someone to a department to avoid confusion.
So, while accuracy is a nice overview, these other metrics give a clearer picture of how well the model is doing.

2. **What activation functions did you choose for your output layers, and why?**

For Department, we used softmax. Think of it like a tie-breaker that decides between the three departments. It gives each department a probability score, and the one with the highest score wins. Plus, all the probabilities add up to 100%, which is neat and easy to interpret.

For Attrition, we also used softmax. Now, you might think, "Why not just use sigmoid since it’s a simple yes/no situation?" Good question! We went with softmax for consistency—it handles probabilities the same way for both outputs, and it still works perfectly for binary classification.

Why softmax rocks: It not only gives the final prediction but also tells us how confident the model is. For example, "This person is 80% likely to stay and 20% likely to leave" is much more insightful than a simple yes or no.

3. **Can you name a few ways that this model might be improved?**

Oh, lots of ways! Let’s break it down:

Fix the Class Imbalance:

Give more "weight" to the smaller, underrepresented groups during training so the model pays more attention to them.
Use techniques like SMOTE to create synthetic samples for the minority classes—kind of like evening out the playing field.
Get Creative with Features:

Combine or engineer new features to highlight patterns the model might miss. It’s like looking at a puzzle from different angles—you start noticing connections you didn’t see before.
Upgrade the Model:

Add more layers or neurons to make the model smarter. Think of it like giving the model a bigger brain to handle complex relationships.
Use dropout layers to prevent overfitting—basically forcing the model to learn how to generalize better.
Try Advanced Techniques:

Switch to XGBoost or LightGBM for better performance on structured data.
If we’re feeling ambitious and have lots of data, we could even try Transformers for state-of-the-art results.
Fine-Tune the Hyperparameters:

Adjust settings like the learning rate, batch size, or number of epochs. It’s like tweaking the knobs on a stereo to get the perfect sound.
Keep an Eye on Metrics:

Focus on precision, recall, and F1-scores, not just accuracy, to make sure improvements actually help where it matters most.
With these tweaks, the model could perform much better, especially for the Department branch and those tricky attrition cases.

